const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_FAILURE = 'REQUEST_FAILURE';
const REQUEST_ERROR = 'REQUEST_ERROR';
const STATUS_CODE = {
    SUCCESS:200

};

export default {REQUEST_SUCCESS, REQUEST_FAILURE, REQUEST_ERROR, STATUS_CODE}